### ISSUE TITLE
Error in recorder if logging.yml is not in current directory 

### ISSUE THREAD

**Issue by TheEimer** [automl/DeepCAVE#88]
I installed deepcave via pip and tried to use the recorder to convert some data. Unfortunately, I got the error that logging.yml does not exist which was only resolved when I copied the file from deepcave/utils to my current path. 
The exact error is in "with (Path() / "logging.yml").open("r") as stream:" and that's what I believe is wrong: the path points to the current directory instead of utils.

Full error log:
`Traceback (most recent call last):`
  `File "/bigwork/nhwpeimt/autorl-offline-data/autorl_dataset/parse_dacbench_data.py", line 5, in <module>
    from deepcave import Recorder, Objective`
 ` File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/site-packages/deepcave/__init__.py", line 45, in <module>`
    `from deepcave.runs.objective import Objective`
 ` File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/site-packages/deepcave/runs/__init__.py", line 21, in <module>`
    `from deepcave.utils.logs import get_logger`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/site-packages/deepcave/utils/logs.py", line 7, in <module>`
    `with (Path() / "logging.yml").open("r") as stream:`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/pathlib.py", line 1119, in open`
    `return self._accessor.open(self, mode, buffering, encoding, errors,`
`FileNotFoundError: [Errno 2] No such file or directory: 'logging.yml'`

**Comment by TheEimer** [comment]
Update: I think this is not a path issue, the problem is that logging.yml is not downloaded when using pip install

**Comment by TheEimer** [comment]
Probaby cause by python 3.10 + pypi, see #96
