### ISSUE TITLE
Trial not serializable

### ISSUE THREAD

**Issue by TheEimer** [automl/DeepCAVE#90]
I'm trying to record a run, but after recorder.end(), when run.save() is called internally, I get the message that:
`TypeError: Object of type Trial is not JSON serializable`
I checked that all elements of trial are serializable themselves (types are down to int, float and dict, so even excluding lists and enum). It's still not writing, though. I don't know if that's a package conflict or what's happening here, but some guidance would be great.

Package versions:
- deepcave 0.2 via pip
- numpy 1.21.4
- python 3.10.11

`Traceback (most recent call last):`
  `File "/bigwork/nhwpeimt/autorl-offline-data/autorl_dataset/parse_dacbench_data.py", line 166, in <module>`
    `r.end(costs=float(reward))`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/site-packages/deepcave/runs/recorder.py", line 163, in end`
    `self.run.save(self.path)`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/site-packages/deepcave/runs/run.py", line 244, in save`
    `f.write(trial)`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/site-packages/jsonlines/jsonlines.py", line 273, in write`
    `line = self._dumps(obj)`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/json/encoder.py", line 199, in encode`
    `chunks = self.iterencode(o, _one_shot=True)`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/json/encoder.py", line 257, in iterencode`
    `return _iterencode(o, 0)`
  `File "/bigwork/nhwpeimt/miniconda3/envs/autorl_dataset/lib/python3.10/json/encoder.py", line 179, in default`
    `raise TypeError(f'Object of type {o.__class__.__name__} '`
`TypeError: Object of type Trial is not JSON serializable`

**Comment by TheEimer** [comment]
Slight update: I transfered the trial to a dict and then it worked, so I think it's really the trial object itself - I'm just confused because this has worked for me previously...

**Comment by TheEimer** [comment]
Probably caused by #96
